// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'debug': string;
  'error': string;
  'info': string;
  'log': string;
  'message': string;
  'warn': string;
}
export const cssExports: CssExports;
export default cssExports;
