// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fullscreen': string;
  'loading': string;
  'message': string;
  'show': string;
}
export const cssExports: CssExports;
export default cssExports;
