name: 'Deploy'
on:
  push:
    branches:
      - build/test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
      - if: ${{ steps.cache-node-modules.outputs.cache-hit == 'false' }}
        name: Install Node Modules
        continue-on-error: true
        run: pnpm i --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build

      # - name: Commit Changes
      #   run: |
      #     git config --local user.email "github-actions[bot]@noreply.github.com"
      #     git config --local user.name "Github Actions [bot]"
      #     git rm --cached -r .
      #     git add dist
      #     git mv dist/* .
      #     git commit -m "Deployment"

      # - name: Deploy
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     force: true
      #     branch: deploy
